name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        node: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Before install
      env:
        ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}
      run: |
        ls
        git clone https://github.com/greenheartgames/greenworks greenworks
        7z x sdk.zip -p${ZIP_PASSWORD}
        mv sdk greenworks/deps/steamworks_sdk
        npm install

    - name: Greenworks install
        run: |
          ls
          cd greenworks
          npm install

    - name: npm install, build, and test
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: true
      run: |
        ls
        npm install
        node index.js